### ISSUE TITLE
More support for buildup

### ISSUE THREAD

**Issue by hongyi-huang** [YoussefRaafatNasry/portfolYOU#21]
You would be highly appreciated if you could offer more support for the following issues.
1. I created a new .md file within /pages, and I supposed it should have be added to the website as a new page like 'about'. But it doesn't work. What more steps should I take?
2. If I'd like to set a specific page as default page (it means if typing 'xxx.github.io', it would be directed to that default page), how can I make it?
Thanks!

**Comment by hongyi-huang** [comment]
The first has been solved by stripping head spaces in front matter.

**Comment by YoussefRaafatNasry** [comment]
_For your second inquiry,_

The `index.html` _in the project's root directory_ is the default page, add your content there and it will be displayed whenever you navigate to `username.github.io` _(as long as you have the `baseurl` empty in your `_config.yml` file)_.

Another way to achieve this, _if you want to name your default file `home.md` instead of `index.html` or move it to a subfolder like `pages/index.html`_, will be by setting the `permalink` to `"/"` in your front matter:

```yml
---
layout: default
permalink: /
---
````
